services:
  postgres:
    image: postgres:latest
    container_name: postgres_piggywise
    environment:
      POSTGRES_USER: manoel
      POSTGRES_PASSWORD: manoel
      POSTGRES_DB: piggywise
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres_network

  quarkus:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: quarkus_app
    environment:
      QUARKUS_DATASOURCE_DB_KIND: postgres
      QUARKUS_DATASOURCE_USERNAME: manoel
      QUARKUS_DATASOURCE_PASSWORD: manoel
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/piggywise
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update
      QUARKUS_HTTP_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
